name: gh-pr-create(1)
description: Run gh-pr-create(1)
inputs:
  branch:
    description: The branch with which the action creates a pull request.
    required: true
  title:
    description: The title for a pull request.
    required: true
  body:
    description: The body for a pull request.
    required: true
  label:
    description: The label for a pull request.
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: git-push(1)
      shell: bash -euxo pipefail {0}
      run: |
        changes=$(git status --short | wc -l)
        if [[ "$changes" == "0" ]]; then
          echo "Nothing to change"
          exit 0
        fi

        cat <<EOD > /tmp/body.txt
          ${{ inputs.body }}
        EOD
        gh pr create --head '${{ inputs.branch }}' --title '${{ inputs.title}}' --label '${{ inputs.label }}' --body-file /tmp/body.txt
